---
- hosts: all
  gather_facts: false
  tasks:
  - set_fact: ansible_python_interpreter=/usr/bin/python3
  - name: Install Java
    dnf:
      name: java-1.8.0-openjdk
      state: present
    become: true
  - name: Install unzip
    dnf:
      name: unzip
      state: present
    become: true
  - name: Install QPid Router
    dnf:
      name: qpid-dispatch-router
      state: present
    become: true
  - name: Install tools
    dnf:
      name: qpid-dispatch-tools
      state: present
    become: true
