---
- hosts: all
  gather_facts: false
  tasks:
  - set_fact: ansible_python_interpreter=/usr/bin/python3
  - name: Install Java
    dnf:
      name: java-1.8.0-openjdk
      state: present
    become: true
  - name: Install unzip
    dnf:
      name: unzip
      state: present
    become: true
  - name: Check for Artemis local
    local_action: stat path=../amq-broker-7.2.0-bin.zip
    register: local_artemis_copy
  - name: Copy Artemis (if local copy found)
    copy:
      src: ../amq-broker-7.2.0-bin.zip
      dest: /tmp/amq-broker-7.2.0-bin.zip
      mode: u=rw,g=r,o=r
    when: local_artemis_copy.stat.exists == true
  - name: Download Artemis (if local copy not found)
    get_url:
      url: http://people.redhat.com/jowest/amq-broker-7.2.0-bin.zip
      dest: /tmp/amq-broker-7.2.0-bin.zip
    when: local_artemis_copy.stat.exists == false
  - name: Create AMQ Broker directory
    file: path=/tmp/amq state=directory
  - name: Unzip Artemis
    unarchive:
      src: /tmp/amq-broker-7.2.0-bin.zip
      dest: /tmp/amq
      remote_src: yes
  - name: Create Broker
    shell: "/tmp/amq/amq-broker-7.2.0/bin/artemis create --user admin --password admin --allow-anonymous /tmp/amq/broker"
    args:
      creates: /tmp/amq/broker
  - name: Configure Broker
    template:
      src: ../templates/broker.xml.j2
      dest: /tmp/amq/broker/etc/broker.xml
  - name: Configure Console
    template:
      src: ../templates/bootstrap.xml.j2
      dest: /tmp/amq/broker/etc/bootstrap.xml
  - name: Start Broker
    command: /tmp/amq/broker/bin/artemis-service start
