---
- hosts: all
  gather_facts: false
  tasks:
  - set_fact: ansible_python_interpreter=/usr/bin/python3
  # - name: Install QPid Router
  #   dnf:
  #     name: qpid-dispatch-router
  #     state: present
  #   become: true
  # - name: Install tools
  #   dnf:
  #     name: qpid-dispatch-tools
  #     state: present
  #   become: true
  - name: Create AMQ Broker directory
    file: path=/tmp/amq state=directory
  - name: Create AMQ Interconnect directory
    file: path=/tmp/amq/router state=directory
  - name: Configure Router
    become: true
    template:
      src: ../templates/{{region_name}}Router.config.j2
      dest: /etc/qpid-dispatch/qdrouterd.conf
  - name: Start Router
    become: true
    command: systemctl start qdrouterd.service
