---
- hosts: all
  gather_facts: false
  tasks:
  - set_fact: ansible_python_interpreter=/usr/bin/python3
  - name: Install Java
    dnf:
      name: java-1.8.0-openjdk
      state: present
    become: true
  - name: Install QPid Router
    dnf:
      name: qpid-dispatch-router
      state: present
    become: true
  - name: Install tools
    dnf:
      name: qpid-dispatch-tools
      state: present
    become: true
  - name: Download Artemis
    get_url:
      url: https://www.apache.org/dyn/closer.cgi?filename=activemq/activemq-artemis/2.6.2/apache-artemis-2.6.2-bin.tar.gz&action=download
      dest: /tmp/apache-artemis-2.6.2-bin.tar.gz
  - name: Create AMQ Broker directory
    file: path=/tmp/amq state=directory
  - name: Create AMQ Interconnect directory
    file: path=/tmp/amq/router state=directory
  - name: Unzip Artemis
    unarchive:
      src: /tmp/apache-artemis-2.6.2-bin.tar.gz
      dest: /tmp/amq
      remote_src: yes
  - name: Create NA Broker
    shell: "/tmp/amq/apache-artemis-2.6.2/bin/artemis create --user admin --password admin --allow-anonymous /tmp/amq/na-broker"
    args:
      creates: /tmp/amq/na-broker
  - name: Configure NA broker
    template:
      src: ../templates/broker.xml.j2
      dest: /tmp/amq/na-broker/etc/broker.xml
    vars:
      artemis_port: 61616
  - name: Configure NA console
    template:
      src: ../templates/bootstrap.xml.j2
      dest: /tmp/amq/na-broker/etc/bootstrap.xml
    vars:
      console_port: 8161
  - name: Create EMEA Broker
    shell: "/tmp/amq/apache-artemis-2.6.2/bin/artemis create --user admin --password admin --allow-anonymous /tmp/amq/emea-broker"
    args:
      creates: /tmp/amq/emea-broker
  - name: Configure EMEA broker
    template:
      src: ../templates/broker.xml.j2
      dest: /tmp/amq/emea-broker/etc/broker.xml
    vars:
      artemis_port: 62626
  - name: Configure EMEA console
    template:
      src: ../templates/bootstrap.xml.j2
      dest: /tmp/amq/emea-broker/etc/bootstrap.xml
    vars:
      console_port: 8262
  - name: Start NA broker
    command: /tmp/amq/na-broker/bin/artemis-service start
  - name: Start EMEA broker
    command: /tmp/amq/emea-broker/bin/artemis-service start
  - name: Configure Router
    template:
      src: ../templates/globalRouter.config.j2
      dest: /tmp/amq/router/router.config
    vars:
      Region1Host: 127.0.0.1
      Region1Port: 61616
      Region2Host: 127.0.0.1
      Region2Port: 62626
  - name: Start Router
    command: /usr/sbin/qdrouterd -d -c /tmp/amq/router/router.config
